default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Hirumi01

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blog_App_development

test:
  <<: *default
  database: Blog_App_test

production:
  <<: *default
  database: Blog_App_production
  username: Blog_App
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
