default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["host_postgres"] %>
  username: <%= ENV["username_postgres"] %>
  password: <%= ENV["password_postgres"] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blog_App_development

test:
  <<: *default
  database: Blog_App_test

production:
  <<: *default
  database: Blog_App_production
  username: Blog_App
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
